language: android
jdk: oraclejdk8
os:
  - linux
  - osx

android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-28.0.3
    - android-28

    # Support library
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

script:
  - chmod +x ./gradlew
  - ./gradlew build --stacktrace